baseURL = 'https://factgraph.docs.symbolic-intelligence.de/'
locale = 'en-us'
title = 'factgraph'
theme = 'hugo-book'

disqusShortname = "my-site"

enableGitInfo = true

copyright = '[© CC BY 4.0](https://creativecommons.org/licenses/by/4.0/legalcode)'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  style = 'base16-snazzy'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
[languages.en]
  label = 'English'
  contentDir = 'content.en'
  weight = 1

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'